openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /event:
    post:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "400":
          description: error
          content:
            application:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    example: error
                  status:
                    type: string
                    example: 400

      requestBody:
        required: true
        content:
          application/json:
            example:
              description: hello world
            schema:
              $ref: '#/components/schemas/myschema'


components:
  schemas:
    myschema:
      title: hello
      description: fffff
      type: object
      properties:
        description:
          description: hello world
          type: string
      required: description