apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Chart.Name }}-image:0.0.1
          imagePullPolicy: Never
          env:
            - name: EVENT_PRODUCER_PORT
              value: {{ .Values.simulator.port | quote }}
            - name: EVENT_PRODUCER_HOST
              value: {{ .Values.simulator.host | quote }}
            - name: EVENTS_PER_SECOND
              value: {{ .Values.simulator.eventPerSecond | quote }}
          ports:
            - name: http-rest
              containerPort: 8080
          volumeMounts:
            - mountPath: "/tmp"
              name: storage-volume
      volumes:
        - name: storage-volume
          emptyDir: { }