apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Chart.Name }}-image:0.0.1
          imagePullPolicy: Never
          # Just sleep forever
          command: [ "sleep" ]
          args: [ "100000" ]
          ports:
            - containerPort: 80